### ISSUE TITLE
Change the menu selector format

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe-browser-provider-electron#15]
So, we use the following approach to get menu item by index:
```js
const menuItem = await getMenuItem('Main Menu > Window > My Window [2]');
```
Besides, we trim spaces in menu items before the comparison.
I think the such approach will cause troubles when a menu item will contains square braces, spaces, tabulation etc.
So we need the other format like
```js
const menuItem = await getMenuItem(["Main Menu", "Window", { item: "My Window", index: 2}]);
```
or
```js
const menuItem = await getMenuItem('"Main Menu" > "Window" > "My Window"[2]');
```
What do you think, @DevExpress/testcafe-docs, @AndreyBelym  ?

**Comment by AlexanderMoskovkin** [comment]
I don't like the current syntax too. What if some item contains the `>` symbol in it's text?

Syntax with an array looks nice, but maybe it's better to move the `index` parameter to the second argument?
```js
const menuItem1 = await getMenuItem(["Main Menu", "Window", "My Window"]);
const menuItem2 = await getMenuItem(["Main Menu", "Window", "Window"], 2);
```

**Comment by helen-dikareva** [comment]
The `>` symbol is located outside the text `"Main Menu"` in Boris's example.
But I like best your last variant:
```
const menuItem2 = await getMenuItem(["Main Menu", "Window", "Window"], 2);
```

**Comment by kirovboris** [comment]
It's not only the last element can be selected by index, so
```const menuItem2 = await getMenuItem(["Main Menu", "Window", "Window"], 2);```
is not working.

**Comment by AlexanderMoskovkin** [comment]
You are right.
Then `const menuItem = await getMenuItem(["Main Menu", "Window", { item: "My Window", index: 2}]);` looks appropriate
