### ISSUE TITLE
Use testcafe-browser-provider-electron with common pluggable electrons apps

### ISSUE THREAD

**Issue by Theomorais** [DevExpress/testcafe-browser-provider-electron#17]
I'm trying to implement testcafe on an atom plugin, your plugin require a .testcafe-electron-rc file.
I think adding a documentation for commons apps on the README can be valuable for non electron developers who only want to test their plugin, for example mainWindowUrl
Thanks for your help.

**Comment by AndreyBelym** [comment]
Hello @Theomorais, it's a really good idea. I think, first step is forming a list of common applications. Let's keep it in this issue.

**Comment by AndreyBelym** [comment]
- [ ] Atom
 
 - [ ] Visual Studio Code

**Comment by Theomorais** [comment]
Hyper.is

**Comment by Nishchit14** [comment]
Is it still in plan? or stale?

**Comment by arubtsov** [comment]
Hi @Nishchit14, this feature is still in our plans, but we cannot give you any time estimates as to when it will be implemented.
