### ISSUE TITLE
Was unable to open the browser

### ISSUE THREAD

**Issue by Theomorais** [DevExpress/testcafe-browser-provider-electron#20]
I am acctualy trying to integrate e2e test on an atom plugin I use your documentation to set up my tests. Here are my specs : "Windows 10 x64 professional, Atom version : 1.18, Node version : 6.9.5"
When I execute the following command : <path_to_testcafe>\testcafe "electron:<path_to_testcafe-electron-rc_directory>" "<path_to_tests>\mytest.js"
Atom launched normaly but the following message is return on my cmd:
ERROR Was unable to open the browser "electron:<path_to_testcafe-electron-rc_directory>" due to error.

Error: Unable to connect
   at NodeDebug._callee2$ (C:\Users\Sansapostrophe\atom-molecule-dev-environment\node_modules\testcafe-browser-provider-electron\lib\node-debug.js:149:35)
   at tryCatch (C:\Users\Sansapostrophe\atom-molecule-dev-environment\node_modules\regenerator-runtime\runtime.js:65:40)
   at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Sansapostrophe\atom-molecule-dev-environment\node_modules\regenerator-runtime\runtime.js:303:22)
   at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Sansapostrophe\atom-molecule-dev-environment\node_modules\regenerator-runtime\runtime.js:117:21)
   at step (C:\Users\Sansapostrophe\atom-molecule-dev-environment\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
   at C:\Users\Sansapostrophe\atom-molecule-dev-environment\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:13

my .testcafe-electron-rc :

{
 "mainWindowUrl": "./index.html",
 "electronPath": "<path_to_atom.exe>"
}

I am not sure if I am doing something wrong.

Thanks,

**Comment by AndreyBelym** [comment]
Hello, @Theomorais! Looks like you have to close all other Atom instances before running TestCafe. Are you sure that there was no `atom.exe` in Process Manager?

**Comment by Theomorais** [comment]
Hello @AndreyBelym, 
When there is no atom.exe process active, when I run TestCafe atom does not launch but the error message still the same.

Thanks,

**Comment by AndreyBelym** [comment]
Is Atom installed in your `Program Files` folder?  If so, can you please try to download an Atom archive (`atom-windows.zip` or `atom-x64-windows.zip`), extract and try to use it?

**Comment by Theomorais** [comment]
"ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure." I have a new error message now. I'll try too find where that error comes from tomorrow.
Thanks for your help.

**Comment by Theomorais** [comment]
After some test I can't find a solution to this bug.
When i launch TestCafe the spinner in the cmd spin for 10 minutes then I got this message:
"ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure."
Thanks for your help.

**Comment by dev-warner** [comment]
Having the same issue described by @Theomorais  last message trying to connect to localhost:3000/ but chrome opens and hangs there then i get the error message "ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure."  I'm on OSX has anyone found out how to resolve this issue?

**Comment by dev-warner** [comment]
@Theomorais  I found how to resolve i answered my question here https://stackoverflow.com/questions/51399372/unable-to-connect-to-a-site-from-testcafe-ide-on-osx/51399448#51399448
