### ISSUE TITLE
app not launching when starting testcafe

### ISSUE THREAD

**Issue by euZebe** [DevExpress/testcafe-browser-provider-electron#25]
I'm not sure where the problem comes from (well, rather from my own code, ok...).
I am trying to add e2e tests to an existing electron app. I followed the steps:
> - install testcafe-browser-provider-electron
> - create a .testcafe-electron-rc
(electron is already installed. I guess I don't have to use the latest version)
> - launch testcafe "electron:/absolute/path/to/projet/root" "<tests_directory>/**/*.js"

doing so, electron starts but I get the following message:
> To run a local app, execute the following on the command line:
> node_modules/electron/dist/electron path-to-app

in the console, once testcafe ends, I get
> ERROR Was unable to open the browser "electron:/absolute/path/to/projet/root" due to error.
> Error: The main window page at file:///absolute/path/to/projet/root/index.html was not loaded.
> Use the mainWindowUrl option to specify one of the following pages as the main window page:
> file:///absolute/path/to/projet/root/node_modules/electron/dist/resources/default_app.asar/index.html

I checked ; the file defined at /absolute/path/to/projet/root/index.html exists. Any idea what I did wrong ?

**Comment by AndreyBelym** [comment]
Hi @euZebe! The [appPath](https://github.com/DevExpress/testcafe-browser-provider-electron#apppath) option description in the Getting Started section is quite misleading. You should use it because otherwise you will have to copy your project into the `$ELECTRON_PATH/resources/app` directory. 

> __appPath__
> Alters path to the application, which, by default, must be located at the [default Electron app directory](https://github.com/electron/electron/blob/master/docs/tutorial/application-distribution.md#application-distribution).
You can use the `appPath` option to override the default path by specifying a new absolute path. Alternatively, you can append a relative path to the path specified after the "electron:" prefix.

If you've placed your `.testcafe-electron-rc` in the same directory with your `package.json`, it's enough to use `'./'` as a value for the `appPath`.
```json
{
    mainWindowUrl: '...',
    appPath: './'
}
```

**Comment by euZebe** [comment]
@AndreyBelym So the path behind `electron:` in the command is the path to the .testcafe-electron-rc file (which could be '.'), and appPath is the path of the electron app (which could also be '.')... ?

Why am I wrong when launching testcafe with `$(npm bin)/testcafe "electron:." "test/**/*.spec.js"` ?
> ERROR Was unable to open the browser "electron:" due to error.
> Error: Cannot find module '/absolute/path/to/projet/root'

**Comment by sijosyn** [comment]
@euZebe Check this stackoverflow answer - https://stackoverflow.com/a/44723909/6353963 . If you add **main** field in package.json file, it will not throw the module not found error. 

`This error can be encountered if you are requireing a module that has a missing or incorrect main field in its package.json. Though the module itself is installed, npm/node has to use a single .js file as an entrypoint to your module. If the main field is not there, it defaults to looking for index.js in your module's folder. If your module's main file is not called index.js, it won't be able to require it.
`

**Comment by tieTYT** [comment]
> If you've placed your `.testcafe-electron-rc` in the same directory with your `package.json`, it's enough to use `'./'` as a value for the `appPath`.
I was having the same issue as the original post, but after following this advice, electron starts up with a blank page. This seems like a step in the right direction.

What is mainWindowUrl supposed to refer to? I've pointed it at an index.html file pre-and post web pack, but either way, a blank page is loaded.

Here is my error:

```
Using locally installed version of TestCafe.
ERROR Was unable to open the browser "electron:" due to error.

Error: The main window page at file:///C:/IdeaProjects/project/.webpack/renderer/main_window/index.html was not loaded.
Use the mainWindowUrl option to specify one of the following pages as the main window page:

http://localhost:3000/main_window
```

**Comment by miherlosev** [comment]
Hi @tieTYT 

The `mainWindowUrl` parameter should contains a URL that was specified for the `Window.openURL` 
 method in your application. According to the error message, you need to specify the `http://localhost:3000/main_window` value for the `mainWindowURL` parameter.
