### ISSUE TITLE
Usage with Electron preload scripts?

### ISSUE THREAD

**Issue by Slapbox** [DevExpress/testcafe-browser-provider-electron#28]
I'm using a preload script in my Electron app, and the HTML page has no call to any JavaScript file. Is this something that's compatible with TestCafe for Electron?

**Comment by AndreyBelym** [comment]
Hi @Slapbox, there must be no problems with preload scripts. Do you have troubles using the provider?

**Comment by Slapbox** [comment]
Thanks for your reply @AndreyBelym. I can't see any way to implement the provider based on the documentation provided. Loading the `app.html` page for my Electron app will not load any JavaScript. Based on the documentation, it seems like the only way I can use this is in a packaged app.

How can I load my preload script with this provider?

**Comment by Slapbox** [comment]
@AndreyBelym is this not possible?

**Comment by Slapbox** [comment]
@AndreyBelym @VasilyStrelyaev @kirovboris @euZebe 

Can any of you let me know if this is possible? I'm guessing the answer is no?

**Comment by AndreyBelym** [comment]
It's hard to understand what's the problem with your app without looking at your app's source code. 

You can load any js script in your app JS files by specifying the `webPreferenced.preload` option in the `BrowserWindow` constructor, or just by adding the `<script src="path/to/script.js">` to your HTML markup.

You don't have to build a package for using the provider, you can set the [appPath](https://github.com/DevExpress/testcafe-browser-provider-electron/blob/master/README.md#apppath) property in `.testcafe-electron-rc` to the directory which contains app's `package.json` file.

The provider assumes that your app will call `BrowserWindow#loadURL` to display the app's main page, and the URL of this page must be specified as the [manWindowUrl](https://github.com/DevExpress/testcafe-browser-provider-electron/blob/master/README.md#mainwindowurl) in `.testcafe-electron-rc`. If you don't use HTML pages at all in your application (e.g. constructing DOM of all pages dynamically in preload scripts), you can't use the provider for now.

**Comment by Slapbox** [comment]
@AndreyBelym thanks for your reply.

What exactly does setting the `mainWindowUrl` in the `.testcafe-electron-rc` do?

The readme says, "_TestCafe waits until Electron loads this page and then runs tests._"

I'm not clear how the HTML page is being loaded from the documentation here. It sounds like TestCafe loads the HTML file and expects the HTML file to load the Javascript. It's really unclear how this works with the `preload` option in Electron's `BrowserWindow`. How is the `preload` script loaded in this situation?

It doesn't sound like TestCafe looks for any scripts related to the `main` process in Electron, so I'm not clear on how it can find the preload script.

**Comment by AndreyBelym** [comment]
TestCafe needs a page served by HTTP/HTTPS server or stored in a file system to run tests. Most Electron applications use HTML pages as a markup of app's windows, so TestCafe have to intercepted window's page and replace it with its version processed by TestCafe's proxy server. When you create a Window in an Electron app, you have to create a window object by calling `window = new BrowserWindow(options)` (and here you can specify your preload script in `options`), and then actually loading a page by using the `window.loadURL(pageUrl)` method. The browser provider intercepts call to the `loadURL` method and replaces `pageUrl` with its proxied version. However, most apps can create multiple windows during their lifecycle (e.g. splash screen and main window), so the provider needs a way to know which window is meant to run tests, and uses the `mainWindowUrl` from `.testcafe-electron-rc` to compare it with `pageUrl` and decide is it the right URL to be replaced.
