### ISSUE TITLE
TestCafe not working with Electron in my example app

### ISSUE THREAD

**Issue by ashleydavis** [DevExpress/testcafe-browser-provider-electron#30]
I have an example electron app (TypeScript & React + Electron) and I'm trying to get TestCafe working with it prior to integrating TestCafe with my commercial application.

I haven't been able to get it working. I've been through your docs multiple times and don't think I've missed anything.

You can get my example project here: https://github.com/ashleydavis/electron-react-typescript-template

Download it, run `npm install` to get dependencies and then run `npm run testcafe` to run my TestCafe test.

Running the command compiles the TypeScript code and then runs TestCafe. The problem is that Electron starts but just contains the welcome page and not my application:

![electron](https://user-images.githubusercontent.com/625126/46564939-08f97b80-c94e-11e8-876b-2952cdabaff2.png)

At this point you can test that the app works in normal Electron by running the command `npx electron .` and you'll see what my example app is supposed to look like:

![example app](https://user-images.githubusercontent.com/625126/46564942-0bf46c00-c94e-11e8-96b5-79fa1eafaa03.png)

**Comment by AndreyBelym** [comment]
The Electron provider expects that your app is ready for distribution and placed in the [app directory](https://github.com/DevExpress/testcafe-browser-provider-electron) in Electron's resources directory. If you don't want to package your app before testing, you should add the [appPath](https://github.com/DevExpress/testcafe-browser-provider-electron#apppath) option to provider's config file, in your case `"appPath": "./"`.
