### ISSUE TITLE
ERROR Unable to find the browser. "electron" is not a browser alias or path to an executable file.

### ISSUE THREAD

**Issue by Slapbox** [DevExpress/testcafe-browser-provider-electron#31]
Running from `/` which contains the following files:

**package.json**
```js
devDependencies: {
   "electron": "^3.0.6",
   "testcafe-browser-provider-electron": "^0.0.6"
}
```

**.testcafe-electron-rc**
```js
{
  "mainWindowUrl": "./app/app.html",
  "appPath": "./"  
}
```

`testcafe electron ./tests/testcafe/test1.js` or `testcafe "electron:./" ./tests/testcafe/test1.js` both lead to:

`ERROR Unable to find the browser. "electron" is not a browser alias or path to an executable file.`

----

I have `testcafe@0.23.0` installed globally on Windows 7 x64. `testcafe -b` returns Firefox, IE, and Chrome, but not Electron. Using an absolute path makes no difference.

**Comment by Slapbox** [comment]
I also tried installing the `devDependencies` as regular dependencies, and even adding `testcafe` as a local dependency, but `electron` is never a recognized browser.

**Comment by Slapbox** [comment]
@AndreyBelym any thoughts on this? I'd love to use TestCafe, but so far, no luck. I've tried `powershell`, `cmd` and `babun` terminals, but the same error every time.

**Comment by AndreyBelym** [comment]
Please, specify your Node.js and NPM/Yarn versions. Try to add `testcafe` to the `devDependencies` and try to execute the following commands in a `cmd` session:
```
npm cache clean -f
rd /s /q node_modules
npm install --production=false
```

If it doesn't help, please follow steps from [this comment](https://github.com/DevExpress/testcafe-browser-provider-browserstack/issues/50#issuecomment-420910813) and post your directory structure here.

**Comment by calumcraig** [comment]
I was facing the same issue on Linux - again TestCafe is installed globally but my Electron app was built as an executable file.

Resolved it by doing `yarn add -D testcafe testcafe-browser-provider-electron`

`testcafe -b electron` then returned:
```Using locally installed version of TestCafe.
"electron:${PATH_TO_ELECTRON_APP}"```

Then when I tried to run a test it launched my app OK.

**Comment by pjc0247** [comment]
Re-installing packages worked for me.

**Comment by Farfurix** [comment]
@calumcraig @pjc0247 

Thank you for sharing your experience with us.
