### ISSUE TITLE
Provide a way to load Chrome extensions 

### ISSUE THREAD

**Issue by miteshsavani** [DevExpress/testcafe-browser-provider-electron#36]
I want to perform offline automation testing in electron app. I found an expected answer (https://testcafe-discuss.devexpress.com/t/how-to-start-chrome-with-offline-mode-on/585/2). 
Here I need to load extension first as per the above mentioned post. I can do that with chrome browser. 
But i am unable to load extension along with electron app

your help would be greatly appreciated!

**Comment by AndreyBelym** [comment]
I apologize for a delayed response. Electron doesn't support loading Chrome extensions via command line flags. You can only call [BrowserWindow.addExtension](https://electronjs.org/docs/api/browser-window#browserwindowaddextensionpath) and [BrowserWindow.addDevToolsExtension](https://electronjs.org/docs/api/browser-window#browserwindowadddevtoolsextensionpath) in your app's code. 

I guess we can introduce a property in `.testcafe-electron-rc` to specify extensions that the provider can load by calling the above functions in the context of your app. But it needs a fair amount of work. If you are interested in implementing this feature, I can show you parts of the code that needs to be modified and answer your question about the development process.
