### ISSUE TITLE
OSX: Cannot open packaged app. (Errors hidden)

### ISSUE THREAD

**Issue by joshuef** [DevExpress/testcafe-browser-provider-electron#37]
I've been trying to get test cafe going for our packaged electron application.

I ran into a few issues:

- My app has spaces in the name. This was breaking things.
- Errors opening applications were never being reported to the console.
- MacOs `open` command was throwing errors: `unable to locate application W`

I've managed to get things going.

I had to `inherit` stdio in order to see (briefly), the above error.

Switching to use a separate `-W` arg for the `open` command fixed that, and then normalizing the app path allows spaces.

I've a branch which I can happily PR in (let me know you want all those changes to separated out / at all? ; I've only tested on osx thus far, so I may be missing some x-platform consideration too :| ). 

(I think using `stdio` is important for being able to see errors, though ATM with the loader, you can only see them briefly unless they throw with a newline).

My branch: https://github.com/joshuef/testcafe-browser-provider-electron/tree/FixOSXOpening

----

Thanks for the work on this so far! It's great to see an alternative to webdriver/selenium etc!

**Comment by AndreyBelym** [comment]
I apologize for a delayed response. Thank you for your contribution. I will try to get some time to merge your changes.

**Comment by joshuef** [comment]
No worries @AndreyBelym . Thanks for taking the time and making something so useful!

Let me know if you want me to PR or something

**Comment by AndreyBelym** [comment]
Thank you, you've already done the hardest part, let me do the rest :)
