### ISSUE TITLE
[Question] Always idle [with modified webview code]

### ISSUE THREAD

**Issue by joshuef** [DevExpress/testcafe-browser-provider-electron#38]
I'm working on modifying the code to be able to access the contents of `webview` tags too. The basics of this seem simple enough, modifying the `BrowserView` prototype overrides and replacing them with `WebContents`.

For example https://github.com/DevExpress/testcafe-browser-provider-electron/blob/master/src/injectable/electron-mocks.js#L71 I have as `WebContents.prototype.loadURL = function (url) {` , and this is working fine. I can get the test code injected into my `webview`!

Buttt, It doesn't progress past the `Idle` page, and I can't for the life of me figure out why. So any tips on where to look  / debug for that would be very much appreciated!

----

I should note: I'm getting no errors in my webview, for eg. I'm only seeing `ERROR Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.` after a timeout (though the test webview shows it's connected).

**Comment by AndreyBelym** [comment]
If I understand correctly, the code in a `webview` is executed in a separate process: https://electronjs.org/docs/api/webview-tag#overview. I think in this case you can't properly mock all required functions. The mocked `loadUrl` function should send a message that the tested URL is successfully injected. I guess it is not possible from a separate `webview` process.

**Comment by joshuef** [comment]
Yeh, webviews are new processes same as `BrowserWindow`s are. So there shouldn't (theoretically) be a problem with the approach as `BrowserWindows` go fine.

Hmm, do you know where this is supposed to be received? @AndreyBelym ? I'm happy to dig around and see if I can get this going. I'm just not sure where to look.

**Comment by AndreyBelym** [comment]
I think the best way to find what's going on is passing the `--inspect-brk` switch to TestCafe and add several breakpoints to the [openBrowser](https://github.com/DevExpress/testcafe-browser-provider-electron/blob/master/src/index.js#L60) function. It should receive a message from the code injected to the Electron main process at [line 84](https://github.com/DevExpress/testcafe-browser-provider-electron/blob/master/src/index.js#L84). I guess that the code injected in a `webview` is executed not in the main process and thus can't send a message to the TestCafe process.
