### ISSUE TITLE
Cannot access `path` attribute on `File` object after file input selection

### ISSUE THREAD

**Issue by kayline** [DevExpress/testcafe-browser-provider-electron#40]
Hello! I'm building an Electron app at @codeforamerica with @zaksoup.

Our Electron app uses a file input to allow the user to select a file for processing. In the onChange handler for the input, we get the `File` object from `event.currentTarget.files`. Electron adds a `path` attribute to the `File` object, which the app parses and displays to the user. When running the app in TestCafe, the `path` attribute is undefined even though the rest of the `File` object is present as expected. This causes the app to throw an error and breaks all tests that need to perform this action. It seems like whatever Electron does to populate that `path` attribute, it's not happening inside TestCafe?

We're going to look into the code here and see if we can figure out what is going on, but wanted to let you know we are running into trouble. Thanks!

**Comment by miherlosev** [comment]
Hi @kayline 

Thank you for the provided detail. I reproduced the problem.
This problem is related to the `testcafe-hammerhead` component. I've created a separate [issue](https://github.com/DevExpress/testcafe-hammerhead/issues/2031) in its repository. Track this to be aware of any progress.
