### ISSUE TITLE
Incompatible with electron 7

### ISSUE THREAD

**Issue by mrfelton** [DevExpress/testcafe-browser-provider-electron#50]
Hi, I'm trying to update my app from electron 6.x to electron 7.x, however testcafe won'y start the app properly under electron 7. It opens up the electron window but it just shows the default electron start page rather than actually loading my app.

After some time it aborts with the following error:

> Unable to establish one or more of the specified browser connections. This can be caused by network issues or remote device failure.

Nothing has changed in my app or test code. No changes were needed to my app when upgrading from electron v6 to v7.

Has this plugin been tested and confirmed to work with electron v7? Can you provide some insights into this issue please?

Thanks.

**Comment by joshuef** [comment]
@AlexKamaev any idea what's needed to get electron 7 support? Is it a `testcafe-browser-provider-electron` or something more fundamental in testcafe? I'd be happy to help out with PRs if there's anything I can get into. Just not really sure where to start.

**Comment by AlexKamaev** [comment]
@joshuef 
I cannot say precisely right now, however, we are already researching the issue.
