### ISSUE TITLE
Support Chrome DevTools protocol for browser actions including video recording

### ISSUE THREAD

**Issue by bbonczek** [DevExpress/testcafe-browser-provider-electron#56]
ENV:

system:  windows 10
node:    v10.14.1
npm:     6.4.1

Steps to reproduce:
1. Run test using electron-browser-provider with record option enabled:
```
 testcafe \"electron:.\" tests/e2e -c 2 --video artifacts/videos --video-options singleFile=true,failedOnly=true",
```
Expect:

Tests pass

Actual:
```
 Warnings (2):
 --
  Video recording is not supported by the "electron:." browser.
 --
  The browser window was resized during the "Parameters properly update
  readonliness" test while TestCafe recorded a video. TestCafe cannot adjust
  the video resolution during recording. As a result, the video content may
  appear broken. Do not resize the browser window when TestCafe records a
  video.
```

**Comment by AndreyBelym** [comment]
Thank you for your inquiry. For now, TestCafe supports recording videos in Chrome and Firefox only. It's a good feature and technically we can implement it in the Electron provider, but we need to invest a lot of time in it.
