### ISSUE TITLE
The main window page at http://localhost:3000 was not loaded.

### ISSUE THREAD

**Issue by nelhu** [DevExpress/testcafe-browser-provider-electron#57]
hi, 
i am using this provider to test my app running in electron, But encountered with this issue
```js
Was unable to open the browser "electron:/Users/huxuezhi/Documents/dev/work/projects/miniapp-demo" due to error

The main window page at http://localhost:3000 was not loaded.
```
which my .testcafe-electron-rc is
```json
{
  "mainWindowUrl": "http://localhost:3000"
}
```
then I run this command
```bash
testcafe "electron:/Users/xxx/<the_testcafe-electron-rc_directory>" index.test.js
```
the error occured above.

I don't know why and what's wrong with my operation?

**Comment by miherlosev** [comment]
Hi @nelhu 

It looks like you specified a wrong URL for the `mainWindowUrl` property.
Update the `testcafe-browser-provider-electron` module to the latest version and run your tests again.
You will see a more extended error message:
```js
Was unable to open the browser "electron:/Users/huxuezhi/Documents/dev/work/projects/miniapp-demo" due to error

The main window page at http://localhost:3000 was not loaded.
Use the mainWindowUrl option to specify one of the following pages as the main window page:
 
 {{#openedUrls}}
```

The `openedUrl` are URL that Electron tried to open on startup. Probably, one of the them is your target URL.
If you can't pick up a valid URL, please send us an example that we can run locally.

**Comment by nelhu** [comment]
the full error are blow: 
```js
Error: The main window page at http://localhost:3000 was not loaded.
Use the mainWindowUrl option to specify one of the following pages as the main window page:

chrome-extension://react-developer-tools/_generated_background_page.html
chrome-extension://redux-devtools/_generated_background_page.html
file:///Users/huxuezhi/Documents/dev/work/projects/miniapp-demo/node_modules/_electron@7.1.9@electron/dist/Electron.app/Contents/Resources/default_app.asar/index.html
```
It did opened an internal page,  But it's not my target page,  my target page is served at 'http://localhost:3000', like the mainWindowUrl specified. so how to set the startup page to 'http://localhost:3000' and make it work? @miherlosev

**Comment by LavrovArtem** [comment]
Could you please provide a small example so that we can reproduce the issue?

I look forward to your response.
