### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by ridenaio** [DevExpress/testcafe-browser-provider-electron#60]
Hi, I use `"testcafe-browser-provider-electron": "0.0.14"`.

Is there any way to run tests in headless mode? I want to setup CI to run my e2e tests.

**Comment by arubtsov** [comment]
Currently, Electron does not support Headless mode natively. For more detail refer to [this](https://github.com/electron/electron/issues/228) thread.

**Comment by AndreyBelym** [comment]
You can try to configure [Xvfb](https://devexpress.github.io/testcafe/documentation/continuous-integration/travis.html#step-3---configure-travis-to-use-xvfb) if you want to test your app in Linux CI. Also, you can try to ask your question [on StackOverflow](https://stackoverflow.com/questions/ask?tags=testcafe) - an amazing platform for users to ask and answer questions.
