### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by joshuef** [DevExpress/testcafe-browser-provider-electron#61]
I'd love to be back on master, and I'm waiting on the last commit there... :bow:

**Comment by AlexKamaev** [comment]
At this moment we are not ready to publish the new release version. However, we can publish an alpha version if you are OK with this.

**Comment by joshuef** [comment]
That'd be great. Just to get that last commit in, then I can rejoin the master branch and get any updates when they come in 👍 

Thanks!

**Comment by AlexKamaev** [comment]
I published the alpha version with the latest changes: https://www.npmjs.com/package/testcafe-browser-provider-electron/v/0.0.15-alpha.1
