### ISSUE TITLE
Electron app shutdown during test run causes TestCafe to hang

### ISSUE THREAD

**Issue by maximojoexpress** [DevExpress/testcafe-browser-provider-electron#67]
I need to shut down our Electron app from within the Electron app UI. However, TestCafe often hangs when I do this as, most likely, it wants to shutdown the app itself and perform some kind of cleanup internally.

I have tried various solutions including hacking the TestCafe source itself and doing the UI shutdown in the various after and afterEach callbacks but have found no reliable solution. Sometimes TestCafe shuts down gracefully, other times it hangs with the error:

ERROR The Electron 3.0.2 / Windows 10 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Originally posted here https://stackoverflow.com/questions/61449043/with-testcafe-and-electron-is-there-a-way-to-allow-the-electron-app-to-shut-its

I have replicated what (hopefully) is the same scenario with the "hash" example Electron app.

### What is your Test Scenario?
Shutting down an electron application during a test run to test our app shutdown functionality.
 
### What is the Current behavior?
TestCafe hangs and eventually displays

>ERROR The Electron 3.1.13 / Windows 10 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.

Debugging through VSCode adding Uncaught Exceptions breakpoints I see:

![image](https://user-images.githubusercontent.com/17994986/80431267-4fe60200-8934-11ea-84b2-a939ffa2f622.png)

 ![image](https://user-images.githubusercontent.com/17994986/80431283-5eccb480-8934-11ea-9564-b246716e712d.png)

### What is the Expected behavior?
TestCafe shuts down gracefully without error.
 
### What is your web application and your TestCafe test code?
See attached file.

### Steps to Reproduce:

1. Run, yarn run testcafe "electron:./" "shutdown.js"
2. When you see "waiting. Close app now!" close the hash app through the Windows "X" close button

or

1. Load app folder in VSCode
2. Check Breakpoints > Unhandled Exceptions (if desired)
3. Run
4. When you see "waiting. Close app now!" close the hash app through the Windows "X" close button

TestCafe hangs and eventually displays

>ERROR The Electron 3.1.13 / Windows 10 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.
 
### Your Environment details:
 
* testcafe version:                   latest
* node.js version:                    10.15.3
* command-line arguments:  yarn run testcafe "electron:./" "shutdown.js"
* browser name and version: Electron
* platform and version:          Windows 10

**Comment by miherlosev** [comment]
Hi @maximojoexpress

There are no updates yet. We are still discussing this idea and will inform you here as soon as we have any results.

**Comment by maximojoexpress** [comment]
Hi there, just wondering if there are any updates on this one.

**Comment by alexey-lin** [comment]
Hi @maximojoexpress. There are no updates yet. At the moment, it looks like some event cannot reach your application when TestCafe calls `closeWindow`. It's not clear why this happens, and additional research is required. We will update this thread as soon as we have any results.
