### ISSUE TITLE
Support Electron 11 (Apple Silicon)

### ISSUE THREAD

**Issue by trungutt** [DevExpress/testcafe-browser-provider-electron#73]
We started to upgrade our Electron version to 11 which is supposed to be tomorrow (according to https://www.electronjs.org/docs/tutorial/electron-timelines). The main reason is that we need to support Apple Silicon hardware (https://www.electronjs.org/blog/apple-silicon). Our app is currently on Electron 10.1.5 (latest stable) with `testcafé@1.9.4` and `testcafe-browser-provider-electron@0.0.15` which works very well.

So I played a bit with `electron@11.0.0-beta.1` and it seemed that we didn't support breaking changes from Electron 11 yet.

Here the error:

<img width="469" alt="Screen Shot 2020-11-16 at 1 45 21 PM" src="https://user-images.githubusercontent.com/18528548/99254050-0b5b7e80-2812-11eb-9e75-7e7f9d47315f.png">

As far as I saw, `process.electronBinding('web_contents')` should be `process._linkedBinding('electron_browser_web_contents');` now according to https://github.com/electron/electron/commit/659e79fc08c6ffc2f7506dd1358918d97d240147. So it leads to `process.electronBinding is not a function` error when starting Electron through the provider.

Please let me know if you need any further information

**Comment by aleks-pro** [comment]
Hello @trungutt,

Thank you for reporting a bug. I was able to reproduce it. We will research it and update this thread as soon as we have any results.

For team: the example is attached. To reproduce the issue, run
```
npm ci
testcafe "electron:." "./tests/test.js"
```
[i73.zip](https://github.com/DevExpress/testcafe-browser-provider-electron/files/5581860/i73.zip)
