### ISSUE TITLE
Mocking HTTP Request not working in Electron App

### ISSUE THREAD

**Issue by ynnelson** [DevExpress/testcafe-browser-provider-electron#78]
I am having issues when trying to Mock HTTP Request in my Electron App using `TestCafe` 

I placed a console log in a mock request to see all the calls that were coming through but none of my http requests originated from my React Component or the main process came through.

```js
const mock = RequestMock()
  .onRequestTo(request => {
    console.log('REQUEST', request); // The full request object

    return request.url.indexOf('/account/beta/verify') > -1; // Here you can set your own rule
  })
  .respond((req, res) => {
    console.log('RESULTS', res);
    return res.setBody('<html><body><h1>OK</h1></body></html>');
  });
```

The only thing that came through were resources request like this one but none of the calls I make in my component using axios.

```js
{
  requestId: '08iNSTIWG',
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.130 Electron/7.1.13 Safari/537.36',
  url: 'file:///Users/myprofile/myapp/app-desktop/app/dist/login.css',
  method: 'get',
  isAjax: false,
  headers: {
    host: '',
    connection: 'keep-alive',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.130 Electron/7.1.13 Safari/537.36',
    accept: 'text/css,*/*;q=0.1',
    referer: 'file:///Users/myprofile/myapp/app-desktop/app/login_window/index.html',
    'accept-encoding': 'gzip, deflate',
    'accept-language': 'en-US'
  },
  body: <Buffer >,
  sessionId: 'TLNqYvUeS'
}
```

Has anyone successfully setup a Mock Request using `TestCafe` in an Electron app? if so what am i missing?

here are some of the versions I am running, I can paste the whole file is useful.
```
"electron": "7.1.13",
"electron-builder": "^22.3.6",
"electron-devtools-installer": "^2.2.4",
"electron-rebuild": "^1.10.0"
"testcafe": "^1.8.0",
"testcafe-browser-provider-electron": "^0.0.14"
```

**Comment by ynnelson** [comment]
I should add that the window that is firing off those calls is a secondary window and not the main window. Not sure if it matters, need to further test to see if the multiple windows is the cause...any input would be appreciated.

**Comment by ynnelson** [comment]
[test.zip](https://github.com/DevExpress/testcafe-browser-provider-electron/files/6268846/test.zip)

I tried to make a sample app with Electron, but in this sample app I run up against CORS issue I am unsure how to resolve because I don't control the API server, I used https://jsonplaceholder.typicode.com/ for a dummy API.

Any guidance here would be helpful.

**Comment by felis2803** [comment]
I didn't manage to reproduce the error you mentioned.
Also, I could not install the application you sent. When trying to install the dependencies, I got an error:
![изображение](https://user-images.githubusercontent.com/34184692/113994116-c934e700-985d-11eb-9e51-634b2901c394.png)

Could you please describe the steps I need to follow to install and run your example so that I can get to the error you mentioned?
