### ISSUE TITLE
Handling multiple electron test instances

### ISSUE THREAD

**Issue by srodritest25** [DevExpress/testcafe-browser-provider-electron#80]
### What is your Test Scenario?
Hi Devexpress team,
I'm working on a project that tests an Electron application, having that in mind we are using Testcafe tool.
Right now the team is implementing a feature that performs an action that must be reflected on different instances of the application.

I have been reviewing your documentation and I found the following article that explains how to handle different instances but just for browser testing:

https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/multiple-browser-windows.html

My question is, do you have in mind implement this feature also for electron execution in the short term?

### What are you suggesting?
Handling multiple electron instances

Regards

**Comment by felis2803** [comment]
Hello,

We do not plan to implement multi-window functionality for Electron in the near future. When we have any news in this regard, we will update this issue.

**Comment by jeia007** [comment]
Hello, Do you know any workaround to this? basically, I just need to get the URI a "new" opened window (opened by the electron packed webpage)

**Comment by felis2803** [comment]
I'm afraid we cannot offer an easy workaround at this time.

**Comment by srodritest25** [comment]
Thanks @felis2803  for the update, I'll be waiting for any new 👍 

Regards!
