### ISSUE TITLE
Add supporting for electron v15

### ISSUE THREAD

**Issue by ofersteinberg** [DevExpress/testcafe-browser-provider-electron#84]
According to the latest version, this plugin supports electron v11.

This task is about adding support for electron v15.

**Comment by miherlosev** [comment]
Hi @ofersteinberg

Thank you for pointing this out.

**Comment by zerocewl** [comment]
Any news here? Electron v11 seems not to be supported any longer and [V16](https://www.electronjs.org/blog/electron-16-0) is already released...

see also: https://www.electronjs.org/blog/electron-15-0#supported-versions

**Comment by miherlosev** [comment]
Hi @zerocewl

Thank you for sharing information about the supported Electron version. At present, we are testing the `testcafe-browser-provider-electron` module with the 11 Electron version. We will consider supporting the latest Electron version (`15`). If this issue is very important for you, the PR is appreciated.

**Comment by GregorBiswanger** [comment]
I'm using Electron 16 and it just opens the Electron Shell. No matter how I try to provide the paths, the app itself will not be loaded.

Electron always opens the same way:

![image](https://user-images.githubusercontent.com/7336300/144730355-e0f59057-b29e-4dad-9fb4-331074a8e887.png)

**Comment by Farfurix** [comment]
@GregorBiswanger 

Hello,

We will also consider upgrading to v16.

**Comment by GregorBiswanger** [comment]
BIG THANK YOU! :)

**Comment by cinan** [comment]
when can we expect updated npm package?

**Comment by miherlosev** [comment]
Hi @cinan 

We are going to release a new version today.

**Comment by vlad-dargel** [comment]
@miherlosev can you add support for electron v19?
