### ISSUE TITLE
Can't take a screenshot on github CI

### ISSUE THREAD

**Issue by EmiM** [DevExpress/testcafe-browser-provider-electron#85]
* node: 12
* ubuntu-20.04
* electron 12.1.0

Hi,
I'm running one e2e electron test on CI. I decided to enable `screenshots-on-fails` to discover why the test fails (it passes locally).
Turned out that I can't do that because:
```
Was unable to take a screenshot due to an error.

  NativeBinaryHasFailedError: The
  /home/runner/work/ZbayLite/ZbayLite/node_modules/testcafe-browser-tools/bin/linux/glibc-64/screenshot
  process failed with the null exit code.
```
I use `DevExpress/testcafe-action@latest`.
The whole output is here: https://github.com/ZbayApp/ZbayLite/runs/4356621701?check_suite_focus=true

Below the 'NativeBinary(...)" error you can see other error saying that "The file at (...) already exists" but it's misleading as the `screenshots` directory is empty.

Notes:
* Running test locally works fine, screenshots are being taken and saved
* I tried `xvfb-run --server-args="-screen 0 1280x720x24" npx testcafe --color --hostname localhost -p '${DATE}_${TIME}_${TEST_ID}.png' -S --screenshots-full-page "electron:." "./**/*.e2e.js` (the same command as used on CI) locally and it failed too, providing identical error

**Comment by holmesworcester** [comment]
It would be great to get this fixed!

**Comment by Dmitry-Ostashev** [comment]
Hi @EmiM ,

This error occurs because testcafe-browser-provider-electron requires the installed Window Manager to be able to take screenshots. Here is a workflow example, which installs Fluxbox before running tests: https://github.com/Dmitry-Ostashev/electron-quick-start/blob/e2e-tests/.github/workflows/functional-testcafe-action.yml .
