### ISSUE TITLE
Support electron helpers in legacy API tests

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe-browser-provider-electron#9]
I import the context menu helper the following way
```js
require('<path_to_node_modules>/testcafe-browser-provider-electron').clickOnMenuItem
```
But it uses ClientFunction inside of test code and doesn't work in legacy API runner.
@AlexanderMoskovkin @AndreyBelym @churkin 
Should we support it in old API? How much efforts does it require?

**Comment by AlexanderMoskovkin** [comment]
I feel we should not. It seems it's a lot of work. Legacy API has no the `testing in electron` feature.

**Comment by kirovboris** [comment]
Ok, then
