### ISSUE TITLE
Add supporting for electron v19

### ISSUE THREAD

**Issue by vlad-dargel** [DevExpress/testcafe-browser-provider-electron#90]
HI! 
We've updated Electron version of our app from 16.0.8 to 19.0.7

And since that I'm catching an error 
```
ERROR Unable to open the "electron:" browser due to the following error:
Error: Unable to connect
```
when trying to run testcafe tests for desktop app.
I'm using "testcafe-browser-provider-electron": "0.0.18"

**Comment by AlenaNaboka** [comment]
Hi, 
@Artem-Babich do you have any updates on it?

**Comment by vlad-dargel** [comment]
Hi @miherlosev when can we expect updated npm package?

**Comment by felis2803** [comment]
Hi @vlad-dargel I'm sorry, but we can't give you an exact date right now.
