### ISSUE TITLE
ERROR The Electron 18.3.5 / Windows 10 browser disconnected. If you did not close the browser yourself, browser performance or network issues may be at fault.

### ISSUE THREAD

**Issue by 2BC-Wasabi** [DevExpress/testcafe-browser-provider-electron#91]
hello there,
i get this issue when i run a test 
`ERROR The Electron 18.3.5 / Windows 10 browser disconnected. If you did not close the browser yourself, browser performance or network issues may be at fault.`

my setup is as follows,

i load a welcome page where the user selects options, then launches the app.

my test works fine until the launch, when i click the launch button i load another url using  
`myappWindow.loadURL(resolveHtmlPath('myapp.html'));`

but then test cafe just hangs until i receive that error 
i tried with both `enableNavigateEvents: true` and `enableNavigateEvents: false`

my .testcafe-electron-rc.js

      const getAppName = () => {
        const extensions = {
          win32: 'myapp.exe',
          linux: 'myapp.AppImage',
          darwin: 'myapp.dmg'
        }
        return extensions[process.platform]
      }
      
      module.exports = {
        mainWindowUrl: "C:\\myapp\\resources\\app.asar\\dist\\renderer\\index.html",
        electronPath:  `C:\\myapp\\myapp.exe`,
        enableNavigateEvents: true
      }

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I reproduced the issue on my side using Electron 16. Since it seems similar to the issue in [https://github.com/DevExpress/testcafe/issues/4701](https://github.com/DevExpress/testcafe/issues/4701), let's continue our discussion there.
