### ISSUE TITLE
Add supporting for electron v19 npm package

### ISSUE THREAD

**Issue by vlad-dargel** [DevExpress/testcafe-browser-provider-electron#95]
https://www.npmjs.com/package/testcafe-browser-provider-electron npm package is still outdated.
Can someone tell when supporting for electron v19 will be released?

**Comment by felis2803** [comment]
@vlad-dargel Sorry for the delayed reply.

Thank you for reminding us of this. We've published a [release](https://github.com/DevExpress/testcafe-browser-provider-electron/releases/tag/v0.0.19) containing the electronv19 support.
